bids_root = 'C:/mis_apps_brainlife/ds000248'
deriv_root = 'C:\mis_apps_brainlife\app_1_init\out_dir'
sessions = all
task = 'audiovisual'
runs = all
conditions = ['Auditory/Left', 'Auditory/Right', 'Visual/Left', 'Visual/Right']
subjects = ['01']
ch_types = ['meg']
data_type = 'meg'
eeg_reference = 'average'
